-- MySQL Script generated by MySQL Workbench
-- Mon Nov 12 15:26:42 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `ID` INT NOT NULL,
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Roles` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `ID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) CHARACTER SET 'dec8' NOT NULL,
  `Users_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Users_ID`),
  INDEX `fk_Customer_Users1_idx` (`Users_ID` ASC),
  CONSTRAINT `fk_Customer_Users1`
    FOREIGN KEY (`Users_ID`)
    REFERENCES `mydb`.`Users` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Journey`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Journey` (
  `ID` INT NOT NULL,
  `JID` INT NOT NULL,
  `Destination` VARCHAR(45) NOT NULL,
  `Distance` VARCHAR(45) NOT NULL,
  `Registration` VARCHAR(45) NOT NULL,
  `Date` DATE NOT NULL,
  `Time` TIME NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Demands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Demands` (
  `ID` INT NOT NULL,
  `Destination` VARCHAR(45) NOT NULL,
  `Date` DATE NOT NULL,
  `Time` TIME NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  `Journey_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Journey_ID`),
  INDEX `fk_Demands_Journey1_idx` (`Journey_ID` ASC),
  CONSTRAINT `fk_Demands_Journey1`
    FOREIGN KEY (`Journey_ID`)
    REFERENCES `mydb`.`Journey` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Drivers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Drivers` (
  `ID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Registration` VARCHAR(45) NOT NULL,
  `Users_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Users_ID`),
  INDEX `fk_Drivers_Users1_idx` (`Users_ID` ASC),
  CONSTRAINT `fk_Drivers_Users1`
    FOREIGN KEY (`Users_ID`)
    REFERENCES `mydb`.`Users` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Demands_has_Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Demands_has_Customer` (
  `Demands_ID` INT NOT NULL,
  `Customer_ID` INT NOT NULL,
  PRIMARY KEY (`Demands_ID`, `Customer_ID`),
  INDEX `fk_Demands_has_Customer_Customer1_idx` (`Customer_ID` ASC),
  INDEX `fk_Demands_has_Customer_Demands_idx` (`Demands_ID` ASC),
  CONSTRAINT `fk_Demands_has_Customer_Demands`
    FOREIGN KEY (`Demands_ID`)
    REFERENCES `mydb`.`Demands` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Demands_has_Customer_Customer1`
    FOREIGN KEY (`Customer_ID`)
    REFERENCES `mydb`.`Customer` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`Drivers_has_Journey`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Drivers_has_Journey` (
  `Drivers_ID` INT NOT NULL,
  `Journey_ID` INT NOT NULL,
  PRIMARY KEY (`Drivers_ID`, `Journey_ID`),
  INDEX `fk_Drivers_has_Journey_Journey1_idx` (`Journey_ID` ASC),
  INDEX `fk_Drivers_has_Journey_Drivers1_idx` (`Drivers_ID` ASC),
  CONSTRAINT `fk_Drivers_has_Journey_Drivers1`
    FOREIGN KEY (`Drivers_ID`)
    REFERENCES `mydb`.`Drivers` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Drivers_has_Journey_Journey1`
    FOREIGN KEY (`Journey_ID`)
    REFERENCES `mydb`.`Journey` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
